### ISSUE TITLE
Great idea!

### ISSUE THREAD

**Issue by coolcalmcollected22** [jgasmussen/Case_Notes.py#2]
No issue to report. I just wanted to say that I applaud the tool and idea. I read the blog post and can totally see many use cases. I like how it is streamlined and simple. Simple purpose, effectively executed. I also saw what you were hoping to implement and wanted to pass on a few links for some other note tools that may provide inspiration (though I am not endorsing any particular one). I also think the Windows executable will be highly useful.

CaseNotes Professional (free to use)
https://first-response.co.uk/casenotes/

Monolith Notes (free to use)
https://www.monolithforensics.com/free-tools

I have a Windows batch script that I had put together prior to reading about yours. It is good to know that there are others thinking along the same lines.

Cheers!

**Comment by jgasmussen** [comment]
Thank you for the kind words. I will check out those links and see if there is anything else that can be added to make the documentation  process more streamlined.
